FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /supply_app

# Installer les outils nécessaires pour la compilation des packages
RUN apt-get update && \
    apt-get install -y gcc build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copier les fichiers de dépendances et installer les packages nécessaires
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Télécharger le modèle spaCy
# RUN python -m spacy download fr_core_news_sm

# Copier tout le reste du code de l'application
COPY src /supply_app/src

# Installer cron
RUN apt-get update && apt-get install -y cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copier le fichier cronjobs et configurer cron
COPY cronjobs /etc/cron.d/cronjobs
RUN chmod 0644 /etc/cron.d/cronjobs
RUN crontab /etc/cron.d/cronjobs

# Exposer le port pour l'application
EXPOSE 8000

# Commande pour lancer cron et Uvicorn simultanément
CMD ["sh", "-c", "cron && uvicorn src.main:app --host 0.0.0.0 --port 8000"]


# Instructions pour la construction et l'exécution de l'image Docker :

# Pour construire l'image Docker :
# docker build -t supply_app_image .

# OU :
# docker build -t supply_app_image -f chemin/relatif/vers/DockerFile .

# Pour exécuter le conteneur Docker :
# docker run -p 8000:8000 supply_app_image
